/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics/index'
import { Route as PhilosophersIndexRouteImport } from './routes/philosophers/index'
import { Route as ChatsIndexRouteImport } from './routes/chats/index'
import { Route as UnsupportedLlmRouteImport } from './routes/unsupported/llm'
import { Route as UnsupportedBrowserRouteImport } from './routes/unsupported/browser'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophersIndexRoute = PhilosophersIndexRouteImport.update({
  id: '/philosophers/',
  path: '/philosophers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsupportedLlmRoute = UnsupportedLlmRouteImport.update({
  id: '/unsupported/llm',
  path: '/unsupported/llm',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsupportedBrowserRoute = UnsupportedBrowserRouteImport.update({
  id: '/unsupported/browser',
  path: '/unsupported/browser',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unsupported/browser': typeof UnsupportedBrowserRoute
  '/unsupported/llm': typeof UnsupportedLlmRoute
  '/chats/': typeof ChatsIndexRoute
  '/philosophers/': typeof PhilosophersIndexRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unsupported/browser': typeof UnsupportedBrowserRoute
  '/unsupported/llm': typeof UnsupportedLlmRoute
  '/chats': typeof ChatsIndexRoute
  '/philosophers': typeof PhilosophersIndexRoute
  '/topics': typeof TopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/unsupported/browser': typeof UnsupportedBrowserRoute
  '/unsupported/llm': typeof UnsupportedLlmRoute
  '/chats/': typeof ChatsIndexRoute
  '/philosophers/': typeof PhilosophersIndexRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unsupported/browser'
    | '/unsupported/llm'
    | '/chats/'
    | '/philosophers/'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unsupported/browser'
    | '/unsupported/llm'
    | '/chats'
    | '/philosophers'
    | '/topics'
  id:
    | '__root__'
    | '/'
    | '/unsupported/browser'
    | '/unsupported/llm'
    | '/chats/'
    | '/philosophers/'
    | '/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UnsupportedBrowserRoute: typeof UnsupportedBrowserRoute
  UnsupportedLlmRoute: typeof UnsupportedLlmRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
  PhilosophersIndexRoute: typeof PhilosophersIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophers/': {
      id: '/philosophers/'
      path: '/philosophers'
      fullPath: '/philosophers/'
      preLoaderRoute: typeof PhilosophersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsupported/llm': {
      id: '/unsupported/llm'
      path: '/unsupported/llm'
      fullPath: '/unsupported/llm'
      preLoaderRoute: typeof UnsupportedLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsupported/browser': {
      id: '/unsupported/browser'
      path: '/unsupported/browser'
      fullPath: '/unsupported/browser'
      preLoaderRoute: typeof UnsupportedBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UnsupportedBrowserRoute: UnsupportedBrowserRoute,
  UnsupportedLlmRoute: UnsupportedLlmRoute,
  ChatsIndexRoute: ChatsIndexRoute,
  PhilosophersIndexRoute: PhilosophersIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
